name = "aiken-lang/109"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/109'"

[repository]
user = "aiken-lang"
project = "109"
platform = "github"

[config.default]
int = 42
bool = true
string = "foo"
bytearray = { bytes = "666f6f", encoding = "base16" }
tuple = [14, false]
list = [1, 2, 3, 4, 5, 6]
nested_tuple = [[true, "foo"], [1, []]]
nested_list = [[1, 2], [3, 4]]
nested_hybrid = [[1, true], [2, false]]
