name = "aiken-lang/acceptance_test_110"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/110'"

[repository]
user = "aiken-lang"
project = "110"
platform = "github"
